name: smart_watches_shop
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  firebase_storage: ^13.4.2
  flutter:
    sdk: flutter

  image_picker: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/app_icons/
    - assets/logo/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/logo/logo.png"

flutter_native_splash:
  color: "#121212"
  image: assets/images/app_logo.png

  android: true
  ios: true

  android_12:
    color: "#121212"
    image: assets/logo/logo.png