// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhSRaSr15zfL6YGSeJpObEe9wnXCb5hE',
    appId: '1:984277649309:web:77927f7463c0009f8e9174',
    messagingSenderId: '984277649309',
    projectId: 'wathesapp-fc191',
    authDomain: 'wathesapp-fc191.firebaseapp.com',
    storageBucket: 'wathesapp-fc191.firebasestorage.app',
    measurementId: 'G-RZKBWV34JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbaQPvbvjZAnH0UGZ0vAKyIb9UNlilB8',
    appId: '1:984277649309:android:23fd3f9209d4113f8e9174',
    messagingSenderId: '984277649309',
    projectId: 'wathesapp-fc191',
    storageBucket: 'wathesapp-fc191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBE87jtT9fK75xIi7zwVcuJayrEJvAP2I4',
    appId: '1:984277649309:ios:ecc954f6b6ef2e7e8e9174',
    messagingSenderId: '984277649309',
    projectId: 'wathesapp-fc191',
    storageBucket: 'wathesapp-fc191.firebasestorage.app',
    iosBundleId: 'com.example.smartWatchesShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBE87jtT9fK75xIi7zwVcuJayrEJvAP2I4',
    appId: '1:984277649309:ios:ecc954f6b6ef2e7e8e9174',
    messagingSenderId: '984277649309',
    projectId: 'wathesapp-fc191',
    storageBucket: 'wathesapp-fc191.firebasestorage.app',
    iosBundleId: 'com.example.smartWatchesShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMhSRaSr15zfL6YGSeJpObEe9wnXCb5hE',
    appId: '1:984277649309:web:2b68c7612299e1d68e9174',
    messagingSenderId: '984277649309',
    projectId: 'wathesapp-fc191',
    authDomain: 'wathesapp-fc191.firebaseapp.com',
    storageBucket: 'wathesapp-fc191.firebasestorage.app',
    measurementId: 'G-1XGZS6LY7W',
  );
}
